### PR TITLE
Update README, parameters, and install script

### PR DESCRIPTION
**Pull request by EricKutschera**

### CODE REVIEW

**Comment by ypnngaa-py** [comment]
Eric, everything looks good. Should we do a squash and merge instead of rebase and merge as several of my commits are separated but for the same task?

Here is my summary of these update: 
1. Update conda requirements
2. Remove the note in README about the old R version
3. Update README to a) add diagram and description for CPM-based screen; b) update IEDB link c) update naming and option for blocklist and MS functions d) update the manuscript title and contact e) other typo fixes
4. Install samtools to a new conda env

**Comment by EricKutschera** [comment]
Hi Yang, doing a squash and merge sounds good to me. And the summary looks good too

**Comment by ypnngaa-py** [comment]
Great. Please merge it with the master as the release V2.0.1. Thanks so
much!

**Comment by EricKutschera** [comment]
I added 1 more commit to update the version numbers: https://github.com/Xinglab/IRIS/commit/598dad3346b4b594639b6e8c8292d934386580de

And I made a v2.0.1 release: https://github.com/Xinglab/IRIS/releases

**Comment by ypnngaa-py** [comment]
Great! Thanks for taking care of the package version and making the release!

**Pull request merged**
